---
name: release
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: false
    secrets: inherit
    needs: [test]
